name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Get SSH and set permissions
        run: |
          mkdir -p ~./ssh
          echo "${{secret.SSH_PRIVATE_KEY}}" > ~/.shh/id_rsa && chmod ~/.ssh/id_rsa
      - name: Deploy using SCP
        run: scp -o StrickHostKeyChecking=no -i ~.ssh/id_rsa -r ./dist/* ${{secret.SSH_USER}}@${{secret.SSH_HOST}}:~/node-app
